name = "weight-loss-fitness-os-app"
compatibility_date = "2026-06-19"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "fitness_os_db"
database_id = "89909110-519b-416f-8792-b3587f361cb3"
preview_database_id = "fitness_os_db_preview"
